title: Apiman
email:
tagline: 'Apiman | Flexible & Extensible Open Source API Management'
description: >- # this means to ignore newlines until "baseurl:"
   Apiman is a flexible open source API Management platform aimed at enterprise users. 
   Combining a rich API design and configuration layer with a fast, modular runtime,
   it's easy to customise Apiman to do whatever you need with simple Java plugins.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.apiman.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: apiman_io
github_username:  apiman

language: en
lang_direction: ltr
color: rgb(61, 94, 129)

# Build settings
error_mode: strict
markdown: kramdown
plugins:
  - jekyll-asciidoc
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - asciidoctor-diagram
  - jekyll-pwa-workbox

sass:
  style: compressed
#  sass_dir: _sass

asciidoc:
  excerpt_separator: "\n// more\n"

asciidoctor:
  base_dir: .
  safe: unsafe
  attributes:
    imagesdir: /assets/images/generated
    imagesoutdir: assets/images/generated
    source-highlighter: highlightjs
    sectanchors: true
    icons: font
    outfilesuffix: ''
    allow-uri-read: ''

# Jekyll Archives
jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag-archive
  permalinks:
    tag: '/blog/tag/:name/'

excerpt_separator: '<!--more-->'

defaults:
  - scope:
      type: "posts"
    values:
      permalink: '/blog/:title/'

# SEO plugin
twitter:
  username: apiman_io
  card: summary
social:
  name: Apiman
  links:
    - https://www.twitter.com/apiman_io
    - https://www.github.com/apiman

pagination:
  enabled: true
  debug: false
  collection: posts
  per_page: 12
  sort_reverse: true
  #paginate_path: "/blog/page:num/"

# RSS/Atom Feed — This is for compatibility with old website
# Does anyone use RSS any more?
feed:
  path: /blog/feed.xml

pwa:
  enabled: true
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
  precache_glob_ignores: # Optional
    - "**/*.html"
