title: 'Apiman'
email:
tagline: 'Apiman | Flexible & Extensible Open Source API Management'
description: >- # this means to ignore newlines until "baseurl:"
   The Apiman project brings an open source development methodology to
   API Management, coupling a rich API design & configuration layer with
   a blazingly fast runtime.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.apiman.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: apiman_io
github_username:  apiman

# Build settings
error_mode: strict
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-paginate-v2

sass:
  style: compressed
#  sass_dir: _sass

asciidoc:
  excerpt_separator: "\n// more\n"

asciidoctor:
  base_dir: .
  safe: unsafe
  attributes:
    source-highlighter: highlightjs
    sectanchors: ''
    icons: font
    outfilesuffix: ''

# Jekyll Archives
jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag-archive
  permalinks:
    tag: '/blog/tag/:name/'

excerpt_separator: '<!--more-->'

defaults:
  - scope:
      type: "posts"
    values:
      permalink: '/blog/:title/'

# SEO plugin
twitter:
  username: apiman_io
  card: summary
social:
  name: Apiman
  links:
    - https://www.twitter.com/apiman_io
    - https://www.github.com/apiman

pagination:
  enabled: true
  debug: true
  collection: posts
  per_page: 12
  sort_reverse: true
  #paginate_path: "/blog/page:num/"

# RSS/Atom Feed — This is for compatibility with old website
# Does anyone use RSS anymore?
feed:
  path: /blog/feed.xml
