title: 'Apiman: Open Source API Management'
email:
description: >- # this means to ignore newlines until "baseurl:"
   The Apiman project brings an open source development methodology to
   API Management, coupling a rich API design & configuration layer with
   a blazingly fast runtime.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.apiman.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: apiman_io
github_username:  apiman

# Build settings
error_mode: strict
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-archives

sass:
  style: compressed
#  sass_dir: _sass

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    source-highlighter: highlightjs
    sectanchors: ''
    icons: font
    outfilesuffix: ''

    # https://github.com/jekyll/jekyll-archives/blob/master/docs/configuration.md
jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag-archive
  permalinks:
    tag: '/blog/tag/:name/'

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
