== Tomcat Quickstart
:tomcat-version: {{ site.data.releases.stable.distros.tomcat }}
:apiman-version: {{ site.data.releases.stable.version }}

Apiman on Apache Tomcat.

=== Prerequisites

* Java 11+
* Refer to https://www.apiman.io/apiman-docs/migration-guide/latest/migrations.html[Migration Guide^] if upgrading.

=== Download
:tc-download-url: https://dlcdn.apache.org/tomcat/tomcat-9/v{tomcat-version}/bin/apache-tomcat-{tomcat-version}.zip
:overlay-download-url: https://github.com/apiman/apiman/releases/download/{apiman-version}/apiman-distro-tomcat-{apiman-version}-overlay.zip

* {tc-download-url}[Download Tomcat {tomcat-version}] — newer micro versions should also work
* {overlay-download-url}[Download Tomcat Apiman overlay {apiman-version}]

=== Install

. Unpack the Apache Tomcat zip
. Unpack the Apiman {apiman-version} Tomcat overlay zip **inside the tomcat directory**

=== Configure

This distribution comes pre-configured with everything you should need to get started.

Please see the https://www.apiman.io/apiman-docs[Installation and User Guide^] for information about how to change Apiman configuration options if you require more customization.

It is possible to use Keycloak instead of Tomcat auth by adding the Keycloak Tomcat valve, but this is an exercise left to the reader.

IMPORTANT: We strongly recommend you change the admin password in `tomcat-users.xml`!

=== Run

. Start Tomcat using the default configuration
. Point your browser at the Apiman UI  http://localhost:8080/apimanui/[`http://localhost:8080/apimanui`^] and log in with `admin`/`admin123!`
