---
layout: post
title:  "Version 1.4 of Apiman is released!"
date: 2018-06-22 14:40:00 BST
author: marc_savy
tags: apiman release
---

I'm delighted to announce that Apiman 1.4 has been released (actually, 1.4.1.Final as of this blog post footnote:[We fixed a couple of bugs spotted in 1.4.0.Final by the community before the blog was written]).

The most important change in this release is that we've upgraded support for Elasticsearch from 1.x to 5.x. It may also support Elasticsearch 2.x, but this isn't officially supported (let us know your experiences).

// more

A significant number of changes across the ES platform were needed to bring this improvement; including in Apiman Gateway, Apiman Manager, Apiman Metrics, test harnesses, and the ES distribution.

If you experience any issues, please report them to us via https://issues.jboss.org/browse/APIMAN/[JIRA], https://github.com/apiman/apiman[GitHub], or https://lists.jboss.org/mailman/listinfo/apiman-user[the mailing list].

== Upgrading

Depending on your approach, to upgrade you can simply use Apiman's https://www.apiman.io/blog/apiman/introduction/overview/backup/export/import/2016/01/27/export-import.html[export-import feature], or upgrade the indices by following Elasticsearch's upgrade guides (likely trickier; I recommend export-import).


We also now launch and manage ES in a significantly different way than previously (as an external process), as the https://www.elastic.co/blog/elasticsearch-the-server[old method is no longer supported].

== Policies can suppress/allow headers in connectors.

A new function has been added to `IPolicyContext` which enables policy authors to explicitly suppress or allow headers that may otherwise have different treatment by default.

[source,java]
----
IConnectorConfig getConnectorConfiguration();
----

Using `IConnectorConfig` a policy author may explicitly override the connector's default filtering of headers. These may vary slightly by platform, but generally would by default filter out headers such as `X-Api-Key`. This is applied at the *end of the policy chain* right before the connection is established.

This feature is useful to unblock certain headers that may otherwise be disallowed, or block headers in such a way that it would even apply to subsequent policies.

Here's an example, using the `suppressRequestHeader` method:

[source,java]
----
void doApply(ApiRequest request, IPolicyContext context, ...) {
    // Get connector config
    IConnectorConfig connectorConfig = context.getConnectorConfiguration();

    // Ban header. Connector will filter this out.
    connectorConfig.suppressRequestHeader("X-SECRET");
    super.doApply(request, context, config, chain);
}
----

Even if another policy in the chain added an `X-SECRET` header, it would still be filtered out footnote:[Unless it explicitly overrode your suppression!].

We hope to expand the functionality of `IConnectorConfig` in future to allow more control of the connector by policies than is possible presently.

== Download 1.4.1.Final

* link:https://downloads.jboss.org/apiman/1.4.1.Final/apiman-distro-vertx-1.4.1.Final.zip[Vert.x (Gateway Only)]


* link:https://downloads.jboss.org/apiman/1.4.1.Final/apiman-distro-wildfly10-1.4.1.Final-overlay.zip[WildFly 10 or EAP 7.1]

* link:https://downloads.jboss.org/apiman/1.4.1.Final/apiman-distro-wildfly11-1.4.1.Final-overlay.zip[WildFly 11]

* link:https://downloads.jboss.org/apiman/1.4.1.Final/apiman-distro-eap7-1.4.1.Final-overlay.zip[EAP 7]

* link:https://downloads.jboss.org/apiman/1.4.1.Final/apiman-distro-tomcat8-1.4.1.Final-overlay.zip[Tomcat 8+]

== Release Notes
* https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12314121&version=12337953[1.4.0.Final]
* https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12314121&version=12338072[1.4.1.Final]

.Enhancements
* https://issues.jboss.org/browse/APIMAN-1334[APIMAN-1334] - Allow policies to suppress/allow headers in connector.

.Bugs
* https://issues.jboss.org/browse/APIMAN-1266[APIMAN-1266] - Error when adding plugin that has previously been deleted (Oracle 12C database)
* https://issues.jboss.org/browse/APIMAN-1296[APIMAN-1296] - The API Key policy plugin (apikey-policy) expects the requestHeader property to be all lowercase as of 1.3.1
* https://issues.jboss.org/browse/APIMAN-1318[APIMAN-1318] - Export/Import of a plugin with policies does not work because of its ID
* https://issues.jboss.org/browse/APIMAN-1320[APIMAN-1320] - Gateway API: Clients still inserted even when invalid
* https://issues.jboss.org/browse/APIMAN-1321[APIMAN-1321] - Elasticsearch data is deleted at tomcat shutdown
* https://issues.jboss.org/browse/APIMAN-1324[APIMAN-1324] - index_already_exists_exception when starting WF quickstart
* https://issues.jboss.org/browse/APIMAN-1335[APIMAN-1335] - ApiKeyPolicy from apikey-policy is throwing an NPE on null connectorConfig using the Vert.x gateway
* https://issues.jboss.org/browse/APIMAN-1337[APIMAN-1337] - SoapAuthorizationPolicy missing i18n messages


.Tasks
* https://issues.jboss.org/browse/APIMAN-892[APIMAN-892] - Upgrade to Elasticsearch 5.x

.Sub-tasks
* https://issues.jboss.org/browse/APIMAN-1323[APIMAN-1323] - Rework test harness to cope better with out of order JSON
* https://issues.jboss.org/browse/APIMAN-1325[APIMAN-1325] - Upgrade Jest HTTP Client for ES
* https://issues.jboss.org/browse/APIMAN-1326[APIMAN-1326] - Upgrade Gateway to ES 5.x
* https://issues.jboss.org/browse/APIMAN-1327[APIMAN-1327] - Upgrade Manager to ES 5.x
* https://issues.jboss.org/browse/APIMAN-1328[APIMAN-1328] - Upgrade metrics to ES 5.x
* https://issues.jboss.org/browse/APIMAN-1329[APIMAN-1329] - Update test harness and tests to ES 5.x
* https://issues.jboss.org/browse/APIMAN-1330[APIMAN-1330] - Update QueryBuilders to ES 5.x
* https://issues.jboss.org/browse/APIMAN-1331[APIMAN-1331] - Switch to EmbeddedElastic instead of (actually) embedded
* https://issues.jboss.org/browse/APIMAN-1332[APIMAN-1332] - Update ES distro to include Elasticsearch distro zip
* https://issues.jboss.org/browse/APIMAN-1333[APIMAN-1333] - Handle EmbeddedElastic hanging process when JVM killed ungracefully.
