---
author: marc_savy
date: 2022-11-27 15:00:00 GMT
tags: apiman release
allow-uri-read: true
---

= Apiman 3, a leap forward
:discussion: https://github.com/orgs/apiman/discussions
:allow-uri-read: true

I'm delighted to announce that I have released Apiman 3.

This is one of the most significant releases in Apiman's history, with a considerable number of new features and behind-the-scenes improvements.

Oh, and I've created a completely new Jekyll-based website for Apiman that will help me better automate releases — I hope you like it!

// more

There is also a new Docker Compose distribution that makes Apiman easier than ever to try out; https://www.apiman.com/download.html[please give it a go^] and {discussion}[let us know your thoughts^].

Feedback and community interaction is critical to the future of the project, so please give us a bit of your time in return for the huge effort that has gone into Apiman 3 🙌.

== What's new?

I'm glad that you asked.
What's not new!

As of Apiman 3, we are now maintaining a comprehensive changelog to ensure that it's absolutely clear what we've added in a new release.
You can see this on https://www.github.com/apiman/apiman/tree/master/CHANGELOG.adoc[our official changelog on GitHub^].
It's also a good way to see the latest features and changes that we're working on as development is in progress.

include::https://gist.githubusercontent.com/msavy/123767f7c3e7bc0a5a44ebd9b5dbff45/raw/80a85ee7ed084a66e8299a54f076fb981ef9d357/test.adoc[tags=3.0.0.Final]
