name: Build New Apiman Website

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install minify
        run: |
          sudo apt update
          sudo apt install minify graphviz

      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.126.0
        with:
          ruby-version: '3.1.2'
          bundler-cache: true

      - name: Build site
        run: |
          bundle exec jekyll build

      - name: Optimise site
        run: |
          # Need to work around bug in version here that is fixed on brew version, so this will probably break later
          # For whatever reason on this version, it nests the input directory inside of output directory.
          minify --sync --all --recursive --html-keep-default-attrvals --html-keep-document-tags --html-keep-quotes --html-keep-whitespace --xml-keep-whitespace --verbose --output=tmp _site/
          mv tmp/_site docs

      - name: Commit generated website
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: "Regenerate apiman.github.io"
          add: -A
          push: false

      - name: Push to `serve` branch
        run: git push origin HEAD:serve -f
